services:
  db:
    image: postgres:16
    container_name: khonic-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: khonic_db
    ports:
      - "5432:5432"
    volumes:
      - khonic_data:/var/lib/postgresql/data

volumes:
  khonic_data:
